name: update-homebrew-formula

on:
  workflow_run:
    workflows: ["release"]
    types:
      - completed

permissions:
  contents: write

jobs:
  update-formula:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get release version from tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract tag from workflow_run event
          TAG=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/jobs --jq '.jobs[0].steps[] | select(.name=="Get the release version from the tag") | .outputs.version')
          if [ -z "$TAG" ]; then
            # fallback: try to get from head_branch
            TAG="${{ github.event.workflow_run.head_branch }}"
          fi
          echo "VERSION=$TAG" >> $GITHUB_ENV

      - name: Download macOS tarball
        run: |
          curl -L -o yo-$VERSION-x86_64-apple-darwin.tar.gz \
            https://github.com/${{ github.repository }}/releases/download/$VERSION/yo-$VERSION-x86_64-apple-darwin.tar.gz

      - name: Calculate macOS sha256
        id: macos_sha
        run: |
          MAC_SHA=$(shasum -a 256 yo-$VERSION-x86_64-apple-darwin.tar.gz | awk '{print $1}')
          echo "sha256=$MAC_SHA" >> $GITHUB_OUTPUT

      - name: Download Linux tarball
        run: |
          curl -L -o yo-$VERSION-x86_64-unknown-linux-musl.tar.gz \
            https://github.com/${{ github.repository }}/releases/download/$VERSION/yo-$VERSION-x86_64-unknown-linux-musl.tar.gz

      - name: Calculate Linux sha256
        id: linux_sha
        run: |
          LINUX_SHA=$(shasum -a 256 yo-$VERSION-x86_64-unknown-linux-musl.tar.gz | awk '{print $1}')
          echo "sha256=$LINUX_SHA" >> $GITHUB_OUTPUT

      - name: Update Homebrew formula
        run: |
          FORMULA_PATH="Formula/yo-bin.rb"
          MAC_SHA=${{ steps.macos_sha.outputs.sha256 }}
          LINUX_SHA=${{ steps.linux_sha.outputs.sha256 }}
          sed -i "s/version '.*'/version '$VERSION'/" $FORMULA_PATH
          sed -i "s|url \"https://github.com/.*/yo-[^/]\+-x86_64-apple-darwin.tar.gz\"|url \"https://github.com/${{ github.repository }}/releases/download/$VERSION/yo-$VERSION-x86_64-apple-darwin.tar.gz\"|" $FORMULA_PATH
          sed -i "s/sha256 \"[a-f0-9]\{64\}\"/sha256 \"$MAC_SHA\"/" $FORMULA_PATH
          sed -i "s|url \"https://github.com/.*/yo-[^/]\+-x86_64-unknown-linux-musl.tar.gz\"|url \"https://github.com/${{ github.repository }}/releases/download/$VERSION/yo-$VERSION-x86_64-unknown-linux-musl.tar.gz\"|" $FORMULA_PATH
          sed -i "s/sha256 \"[a-f0-9]\{64\}\"/sha256 \"$LINUX_SHA\"/2" $FORMULA_PATH

      - name: Commit and push updated formula
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Formula/yo-bin.rb
          git commit -m "chore(homebrew): update yo-bin.rb for $VERSION"
          git push
